apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ba0fh12y7-python
  janus-idp.io/tekton: ba0fh12y7-python
  backstage.io/kubernetes-id: ba0fh12y7-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ba0fh12y7-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
